version: '3.4'

services:
  dev_influxdb:
    image: influxdb:1.8
    container_name: influxdb_dev 
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DB=k6
    network_mode: host
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  dev_jupyter:
    build: ./jupyter
    container_name: jupyter_dev
    volumes:
      - ./jupyter/notebooks/:/home/jovyan/notebooks
      - ./jupyter/k6_scripts:/home/jovyan/k6_scripts
    container_name: jupyter
    network_mode: host
    environment:
     - JUPYTER_TOKEN=admin
     - GRANT_SUDO=yes
  
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DB=k6
    volumes:
      - /home/master_data/influxdb:/var/lib/influxdb

  jupyter:
    image: engisaacnewton/jupyter_benchmark:latest
    container_name: jupyter
    ports:
     - 8888:8888
    environment:
     - JUPYTER_TOKEN=admin
     - GRANT_SUDO=yes
  
  grafana:
    image: grafana/grafana:latest
    # ports:
    #   - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    network_mode: host
  
  k6:
    image: loadimpact/k6:latest
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://localhost:8086/k6
    volumes:
      - ./k6_scripts:/k6_scripts
    network_mode: host
